casdoor/casdoor-go-sdk

auth/token.go, auth/user.go, auth/util.go
Signed-off-by: sh1luo <690898835@qq.com>
=> fix: improve code comments

.github/workflows/ci.yml, .releaserc.json
Fix: https://github.com/casdoor/casdoor-go-sdk/issues/7
=> feat: semantic release

auth/token.go
Signed-off-by: Steve0x2a <stevesough@gmail.com>
=> feat: add refresh_token support

auth/user.go
=> fix: use DoGetBytesRaw instead of DoGetBytes in users.go

README.md, auth/auth.go, auth/jwt.go, auth/token.go
Certificate is a more accurate name.
=> feat: Rename arg from jwtSecret to certificate

README.md, casdoorsdk/application.go, casdoorsdk/auth.go, casdoorsdk/base.go, casdoorsdk/email.go, casdoorsdk/jwt.go, casdoorsdk/organization.go, casdoorsdk/permission.go, casdoorsdk/resource.go, casdoorsdk/sms.go, casdoorsdk/token.go, casdoorsdk/url.go, casdoorsdk/user.go, casdoorsdk/util.go
=> feat: use `casdoorsdk` as the pkg name

casdoorsdk/user.go
=> feat: add `GetUserByUserId`

README.md
=> chore(doc): add install and import guide

casdoorsdk/application.go, casdoorsdk/organization.go, casdoorsdk/permission.go, casdoorsdk/resource.go, casdoorsdk/user.go
`xorm` tag in there is useless.
=> chore: remove the useless `xorm` tag

casdoorsdk/role.go, casdoorsdk/user.go
Go version for: https://github.com/casdoor/casdoor-java-sdk/issues/28
=> feat: add roles and permissions for user

casdoorsdk/application.go, casdoorsdk/base.go, casdoorsdk/email.go, casdoorsdk/organization.go, casdoorsdk/permission.go, casdoorsdk/resource.go, casdoorsdk/sms.go, casdoorsdk/user.go, casdoorsdk/util.go
=> feat: add `SetPassword` API and expose `DoPost` API

casdoorsdk/base.go, casdoorsdk/permission.go
Add permission CRUD(Create, Read, Update, Delete) APIs
=> feat: add permission APIs

casdoorsdk/base.go, casdoorsdk/role.go
Add role CRUD(Create, Read, Update, Delete)
Add role pagination
=> feat: add role APIs

casdoorsdk/permission.go, casdoorsdk/role.go
Support roles, permissions pagination with field & value
=> feat: pagination with field value

casdoorsdk/permission.go, casdoorsdk/role.go, casdoorsdk/user.go
- add GetPaginationUsers API
- replace input `fv ...string` by `queryMap map[string]string`
=> feat: add GetPaginationUsers() API

README.md
Signed-off-by: seazhang <sealingp@163.com>
=> fix: README.md go get github.com/casdoor/casdoor-go-sdk@latest

README.md
fix the badges routes
https://github.com/badges/shields/issues/8671
=> fix(badges): fix the badges routes

casdoorsdk/base.go, casdoorsdk/enforce.go, casdoorsdk/util.go
Support Enforce and BatchEnforce methods
=> feat: add enforce, batch-enforce method

casdoorsdk/base.go, casdoorsdk/user.go
=> feat: update user by id

casdoorsdk/user.go
Sync user model with the latest casdoor's release.
Add groups, for example
=> feat: sync user model

casdoorsdk/enforce.go
Since casdoor's api for enforce and batch-enforce was changed golang-sdk has to be changed as well.
=> feat: support new Enforce() and BatchEnforce() APIs

casdoorsdk/enforce.go
the current result just get the first result, but the response data return a slice bool
=> fix: check all results in Enforce()

casdoorsdk/base.go
Relative to MR [1993](https://github.com/casdoor/casdoor/pull/1993) in Casdoor, currently the API can response error if facing problems. But we still do not check this right now, it can lead to a panic, this MR will cover this part.
Testing code:
```go
func main() {
casdoorsdk.InitConfig(
"http://localhost:8000",
"37fcf22637d98fc2c99e",
"a272de88b58f360c06affc6cec5a68e048b5514f", 
"cert-built-in",
"built-in",
"app-built-in");
permissions, err := casdoorsdk.GetPermissions();
if err != nil {
fmt.Println(err.Error())
} else {
for _, permission := range permissions {
fmt.Printf("%v\n", permission.Name)
}
}
permissions, _, err = casdoorsdk.GetPaginationPermissions(0, 10, make(map[string]string, 0));
if err != nil {
fmt.Println(err.Error())
} else {
for _, permission := range permissions { …
```
=> feat: check error in getbytes function

casdoorsdk/resource.go
Also preparing for [Casibase#3](https://github.com/casbin/casibase/issues/3)
By the way, there is barely no swagger docs for [Resource API](https://demo.casdoor.com/swagger/#/Resource%20API)
=> feat: support get-resource apis

casdoorsdk/cert.go
caswaf has a requirement of loading certs.
=> fix: add get certs api

casdoorsdk/application.go, casdoorsdk/base.go
Fixed bugs in Application related apis.
=> fix: fix bugs in application related APIs

casdoorsdk/subscription.go, casdoorsdk/util.go
Fix: https://github.com/casdoor/casdoor-go-sdk/issues/97
=> fix: fix bug in GetPaginationSubscriptions() API

casdoorsdk/jwt.go
Add jwt token type to Claims struct to check if it is an access token or refresh token.
=> feat: add JWT token type

casdoorsdk/token.go, go.mod, go.sum
Reference: https://casdoor.org/docs/how-to-connect/oauth/#how-to-verify-access-token
=> feat: add IntrospectToken() API

casdoorsdk/transaction.go, casdoorsdk/transaction_global.go, casdoorsdk/transaction_test.go, casdoorsdk/util_modify.go
Fix: https://github.com/casdoor/casdoor/issues/2763
=> feat: add transaction APIs

casdoorsdk/user.go
Fix: https://github.com/casdoor/casdoor-go-sdk/issues/109
=> feat: add ExternalId in User struct

casdoorsdk/role.go
groups is missing in role struct
=> feat: add missing groups for role

casdoorsdk/application.go, casdoorsdk/email.go, casdoorsdk/email_global.go, casdoorsdk/email_test.go, casdoorsdk/sms.go, casdoorsdk/sms_global.go, casdoorsdk/sms_test.go
Add API SendEmailByProvider and SendSmsByProvider
=> feat: add SendEmailByProvider and SendSmsByProvider APIs, add back Application.CertObj

casdoorsdk/plan.go
Fix: https://github.com/casdoor/casdoor-go-sdk/issues/131
=> feat: update Plan struct fields

casdoorsdk/application.go
=> feat: update SigninItem struct to add CustomCss field

casdoorsdk/organization.go
Introduce a new field in the Organization struct. Reference from https://github.com/casdoor/casdoor/blob/master/object/organization.go#L60
=> feat: add Organization.HasPrivilegeConsent field

casdoorsdk/policy.go, casdoorsdk/policy_global.go, casdoorsdk/policy_test.go
Refactored GetFilteredPolicies to accept new post data
=> feat: improve GetFilteredPolicies() method

casdoorsdk/mfa.go
Similar to: https://github.com/casdoor/casdoor-nodejs-sdk/pull/75
=> feat: add MFA (Multi-Factor Authentication) support to Go SDK

casdoorsdk/user.go
Fix: https://github.com/casdoor/casdoor-go-sdk/issues/173
=> feat: add Invitation and InvitationCode fields into user definition
